### ISSUE TITLE
Polyring ded?

### ISSUE THREAD

**Issue by dragmakex** [XYQuadrat/polyring#110]
When I go to polyring.ch I get this:

![image](https://github.com/XYQuadrat/polyring/assets/31779042/9f0f0ac3-f8b9-4ae2-aaba-4addedd41f7d)

**Comment by XYQuadrat** [comment]
Known problem, I'm having issues with my reverse proxy right now. Will try to fix ASAP.

**Comment by dragmakex** [comment]
All good, no worries :)
